import java.util.Scanner;

public class Player_Name 
{

	public static String Player_Name1="User1"; //Sets default global variable to "Player" that can be overwritten when user enters the user input!
	public static void main (String player_Name1)
	{
		Input_Player_Name();
	}
	
	public static String Input_Player_Name()
	{
		Scanner Players_name1= new Scanner(System.in);
		System.out.println("Welcome to MasterMind please enter your player name to play:");
		System.out.println("Enter your 6 length long"+"["+"Player"+"]"+"name here!");
		boolean Enter_Player_Name=false;
		while(Enter_Player_Name==false) 
		{
			String	players_name = Players_name1.nextLine();
			if (players_name.length()==6)
			{
				Enter_Player_Name=true;
				Player_Name1= players_name;
			}
			if(players_name.length()!=6) // Limits player name to 6 in terms of player length
			{  
				Enter_Player_Name=false;
				System.err.println("Invalid player name. You must enter a 6 letter PLAYER NAME!");
				return Input_Player_Name(); // Ensures the invalid username isn't displayed causes crash in code if removed. RETURNS THE PLAYERNAME THAT MATCHES THE CONDITION OF BEING LESS THE 6 CHARACTERS LONG
			}
			String rules = "Welcome"+"("+players_name.toUpperCase()+"!"+")"+", Mastermind is a code-breaking game. The purpose is to guess the secret code decided by the computer\n"
					+ "but there is a twist and that is it's generated by you! There is a vast amount of colours to choose from known as the range.\n"
					+ "The range is made up by (6-10) colours and from there a (3-4) digit code can be generated also chosen by you.\n"
					+ "You win if the code is matched within the Max-LIMIT of 12 attempts, however you can choose how many attempts you get.\n"
					+ "Every time you try to guess the gameboard returns a code formed by(+) and (-) symbols: \n"
					+ "(+) ones indicate the number of characters of the right color and in the right position, \n"
					+ "(-) ones indicate the characters of the right color but in the wrong position.\n"
					+ "You should only input these colours ['R','G','B','Y','O','P','W','C','T','N']\n"
					+ "I hope you enjoy and fun with the game MasterMind! Made by: Jatinder\n";
			System.out.println(rules);
			}
			return ""; //returns empty space and continuous on with the method
	}
	public static String In_Game_Player_Name()
	{
		return Player_Name1;
	}
}

